baseURL = "https://awesome-hamilton-c5d7ea.netlify.com/"
languageCode = "zh-cn"
title = "Alr2d2's Psycho"
theme="cactus-plus"
author="Alr2d2"
[params]
    customCSS = ["css/override.css", "css/atom-one-light.css"]