baseURL = "https://jp.al002.dev/"
languageCode = "zh-cn"
title = "al002's Psycho"
theme = "cactus-plus"
author = "al002"
ignoreFiles = [ "\\.#" ]
googleAnalytics = "UA-112759972-1"
[params]
    customCSS = ["css/override.css", "css/atom-one-light.css"]
    enableGoogleAnalytics = true
